#!/bin/bash -e

echo "-------> AWS"
export TEST_AWS_CLI="ship_aws_cli"
# since resources here have dashes Shippable replaces them and UPPER cases them
export TEST_AWS_CLI_UP=$(echo $TEST_AWS_CLI | awk '{print toupper($0)}')
export TEST_AWS_INTEGRATION_ACCESS_KEY_ID=$(eval echo "$"$TEST_AWS_CLI"_INTEGRATION_AWS_ACCESS_KEY_ID")
export TEST_AWS_INTEGRATION_SECRET_ACCESS_KEY=$(eval echo "$"$TEST_AWS_CLI"_INTEGRATION_AWS_SECRET_ACCESS_KEY")
export TEST_AWS_INTEGRATION_URL=$(eval echo "$"$TEST_AWS_CLI"_INTEGRATION_URL")
echo TEST_AWS_INTEGRATION_ACCESS_KEY_ID=${#TEST_AWS_INTEGRATION_ACCESS_KEY_ID}
echo TEST_AWS_INTEGRATION_SECRET_ACCESS_KEY=${#TEST_AWS_INTEGRATION_SECRET_ACCESS_KEY}
echo TEST_AWS_INTEGRATION_URL=$TEST_AWS_INTEGRATION_URL

echo "------> ECR"
export TEST_ECR_CLI="ship_ecr_cli"
export TEST_ECR_CLI_UP=$(eval echo $TEST_ECR_CLI | awk '{print toupper($0)}')
export TEST_ECR_INTEGRATION_ACCESS_KEY_ID=$(eval echo "$"$TEST_ECR_CLI_UP"_INTEGRATION_AWS_ACCESS_KEY_ID")
export TEST_ECR_INTEGRATION_SECRET_ACCESS_KEY=$(eval echo "$"$TEST_ECR_CLI_UP"_INTEGRATION_AWS_SECRET_ACCESS_KEY")
echo TEST_ECR_INTEGRATION_ACCESS_KEY_ID=${#TEST_ECR_INTEGRATION_ACCESS_KEY_ID}
echo TEST_ECR_INTEGRATION_SECRET_ACCESS_KEY=${#TEST_ECR_INTEGRATION_SECRET_ACCESS_KEY}

echo "-------> Docker"
export TEST_DH_CLI="ship_dh_cli"
export TEST_DH_CLI_UP=$(echo $TEST_DH_CLI | awk '{print toupper($0)}')
export TEST_DH_INTEGRATION_USERNAME=$(eval echo "$"$TEST_DH_CLI_UP"_INTEGRATION_USERNAME")
export TEST_DH_INTEGRATION_PASSWORD=$(eval echo "$"$TEST_DH_CLI_UP"_INTEGRATION_PASSWORD")
export TEST_DH_INTEGRATION_EMAIL=$(eval echo "$"$TEST_DH_CLI_UP"_INTEGRATION_EMAIL")
echo TEST_DH_INTEGRATION_USERNAME=$TEST_DH_INTEGRATION_USERNAME
echo TEST_DH_INTEGRATION_PASSWORD=${#TEST_DH_INTEGRATION_PASSWORD}
echo TEST_DH_INTEGRATION_EMAIL=$TEST_DH_INTEGRATION_EMAIL

echo "-------> GCR"
export TEST_GCR_CLI="ship_gcr_cli"
export TEST_GCR_CLI_UP=$(echo $TEST_GCR_CLI | awk '{print toupper($0)}')
export TEST_GCR_INTEGRATION_JSON_KEY=$(eval echo "$"$TEST_GCR_CLI_UP"_INTEGRATION_JSON_KEY")
echo TEST_GCR_INTEGRATION_JSON_KEY=${#TEST_GCR_INTEGRATION_JSON_KEY}

echo "-------> GKE"
export TEST_GKE_CLI="ship_gke_cli"
export TEST_GKE_CLI_UP=$(echo $TEST_GKE_CLI | awk '{print toupper($0)}')
export TEST_GKE_INTEGRATION_JSON_KEY=$(eval echo "$"$TEST_GKE_CLI_UP"_INTEGRATION_JSON_KEY")
export TEST_GKE_INTEGRATION_URL=$(eval echo "$"$TEST_GKE_CLI_UP"_INTEGRATION_URL")
echo TEST_GKE_INTEGRATION_URL=$TEST_GKE_INTEGRATION_URL

echo "-------> QUAY"
export TEST_QUAY_CLI="ship_quay_cli"
export TEST_QUAY_CLI_UP=$(echo $TEST_QUAY_CLI | awk '{print toupper($0)}')
export TEST_QUAY_INTEGRATION_USERNAME=$(eval echo "$"$TEST_QUAY_CLI_UP"_INTEGRATION_USERNAME")
export TEST_QUAY_INTEGRATION_PASSWORD=$(eval echo "$"$TEST_QUAY_CLI_UP"_INTEGRATION_PASSWORD")
export TEST_QUAY_INTEGRATION_URL=$(eval echo "$"$TEST_QUAY_CLI_UP"_INTEGRATION_URL")
export TEST_QUAY_INTEGRATION_EMAIL=$(eval echo "$"$TEST_QUAY_CLI_UP"_INTEGRATION_EMAIL")
export TEST_QUAY_INTEGRATION_ACCESSTOKEN=$(eval echo "$"$TEST_QUAY_CLI_UP"_INTEGRATION_ACCESSTOKEN")
echo TEST_QUAY_INTEGRATION_USERNAME=$TEST_QUAY_INTEGRATION_USERNAME
echo TEST_QUAY_INTEGRATION_PASSWORD=${#TEST_QUAY_INTEGRATION_PASSWORD}
echo TEST_QUAY_INTEGRATION_URL=$TEST_QUAY_INTEGRATION_URL
echo TEST_QUAY_INTEGRATION_EMAIL=$TEST_QUAY_INTEGRATION_EMAIL
echo TEST_QUAY_INTEGRATION_ACCESSTOKEN=${#TEST_QUAY_INTEGRATION_ACCESSTOKEN}

